FROM public.ecr.aws/lambda/provided:al2023

# 静的ffmpegバイナリをダウンロード（最も確実な方法）
RUN dnf update -y && \
    dnf install -y tar xz && \
    dnf clean all

# # 公式の静的ビルドをダウンロード（x86_64 版）
RUN curl -L -o /tmp/ffmpeg.tar.xz \
        https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz && \
    tar -C /opt -xJf /tmp/ffmpeg.tar.xz && \
    mv /opt/ffmpeg-*-static /opt/ffmpeg && \
    ln -s /opt/ffmpeg/ffmpeg  /usr/local/bin/ffmpeg  && \
    ln -s /opt/ffmpeg/ffprobe /usr/local/bin/ffprobe && \
    rm -f /tmp/ffmpeg.tar.xz

# # ffmpegのテスト
# RUN /usr/local/bin/ffmpeg -version

# # 環境変数の設定
# ENV PATH="/usr/local/bin:${PATH}"
# ENV FFMPEG_PATH="/usr/local/bin/ffmpeg"

