AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Go Radio Lambda

Resources:
  RadioFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 900
      Environment:
        Variables:
          VERBOSE: "false"
          DEFAULT_DURATION: "60"
          DEFAULT_OUTPUT_DIR: "/tmp/radiko"
          FFMPEG_PATH: "/usr/local/bin/ffmpeg"
          UPLOAD_BUCKET: "radio-transcribe"
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      # The DockerTag should be a single tag string. Using a value with a
      # colon results in an invalid Docker reference when SAM prepends the
      # function name. To keep the tag descriptive while valid, use a hyphen
      # instead of a colon.
      DockerTag: go-radio-latest
