AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Go Radio Lambda

Resources:
  RadioFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 900
      Environment:
        Variables:
          VERBOSE: "false"
          DEFAULT_DURATION: "60"
          DEFAULT_OUTPUT_DIR: "/tmp/radiko"
          FFMPEG_PATH: "/usr/local/bin/ffmpeg"
          UPLOAD_BUCKET: "radio-transcribe"
      Policies:
        - S3WritePolicy:
            BucketName: "radio-transcribe"
      Events:
        ScheduleV2Event:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: cron(10 22 ? * MON-THU *)
            ScheduleExpressionTimezone: "Asia/Tokyo"
            Input: |
              {
                "station": "TBS",
                "start": "",
                "duration": 120,
                "output": "yyyymmdd_hhmm.aac"
              }
            State: ENABLED
            Name: radio-schedule-event
            Description: radio-schedule-event


    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      # The DockerTag should be a single tag string. Using a value with a
      # colon results in an invalid Docker reference when SAM prepends the
      # function name. To keep the tag descriptive while valid, use a hyphen
      # instead of a colon.
      DockerTag: go-radio-latest
